# Generated by Django 3.1.1 on 2020-10-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_inventroy_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventroy',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
